@startuml
title SmartHome Web Application Component Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Container_Boundary(SmartHomeSystem, "SmartHome System") {
  Container(HomeManagmentService, "HomeManagment Service", "Node.js", "")
  Container(Database, "Database", "PostgreSQL", "")
}

Container(HomeManagmentService, "HomeManagment Service", "Node.js", "") {
  Component(SensorsController, "SensorsController", "Manages sensors")
  Component(LocationsController, "LocationsController", "Manages home and locations")
  Component(BusinessLogic, "Business Logic", "Business logic")
  Component(RepositoryLayer, "Repository Layer", "Data access logic")
}

Rel(SensorsController, BusinessLogic, "Calls business logic")
Rel(LocationsController, BusinessLogic, "Calls business logic")
Rel(BusinessLogic, RepositoryLayer, "Reads/Writes data")
Rel(RepositoryLayer, Database, "Reads/Writes user data")

@enduml