@startuml
title SmartHome Web Application Component Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

(SmartHomeSystem, "SmartHome System") {
  Container(TelemetryService, "TelemetryService", "Node.js", "")
  ContainerDb(Database, "Database", "PostgreSQL", "")
}

Container(TelemetryService, "TelemetryService", "Node.js", "") {
  Component(TemperatureController, "TemperatureController", "")
  Component(BusinessLogic, "Business Logic", "Business logic")
  Component(RepositoryLayer, "Repository Layer", "Data access logic")
}

Rel(TemperatureController, BusinessLogic, "Calls business logic")
Rel(BusinessLogic, RepositoryLayer, "Reads/Writes data")
Rel(RepositoryLayer, Database, "Reads/Writes user data")

@enduml