@startuml
title SmartHome Container Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(user, "User", "A user of the system")
Person(sensor, "Sensor", "aka Temperature API")

System(SmartHomeSystem, "SmartHome System", "System managing sensors and temperature")

Container_Boundary(SmartHomeSystem, "SmartHome System") {
  Container(Monolith, "Monolith", "Old Monolith App. Can be turned into Gateway API")

  Container(MobileApp, "Mobile Application", "Kotlin, Swift", "Allows users to manage their home")
  Container(SensorsService, "Sensors Service", "Node.js", "")
  Container(TelemetryService, "Telemetry Service", "Node.js", "")
  Container(Database, "Database", "PostgreSQL", "")
}

Rel(user, MobileApp, "")
Rel(Monolith, sensor, "")
Rel(MobileApp, Monolith, "")
Rel(Monolith, SensorsService, "")
Rel(Monolith, TelemetryService, "")
Rel(SensorsService, Database, "")
Rel(TelemetryService, Database, "")
Rel(TelemetryService, sensor, "")

@enduml