@startuml
title SmartHome Devices Controller Code Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml



Boundary(businessLogic, "Business Logic") {
  class RegisterDeviceUseCase {
  }

  class UpdateDeviceUseCase {
  }

  class DeleteDeviceUseCase {
  }

  class FindOneDeviceUseCase {
  }

  class FindManyDeviceUseCase {
  }

  interface IDeviceRepository {
    + update()
    + create()
    + remove()
    + findOne()
    + findMany()
  }

  interface IUseCase {
    + execute()
  }
}

class DevicesController {
  + registerDevice()
  + updateDevice()
  + deleteDevice()
  + findOneDevice()
  + findManyDevice()
}

RegisterDeviceUseCase -> IUseCase
RegisterDeviceUseCase -> IDeviceRepository

UpdateDeviceUseCase -> IUseCase
UpdateDeviceUseCase -> IDeviceRepository

DeleteDeviceUseCase -> IUseCase
DeleteDeviceUseCase -> IDeviceRepository

FindOneDeviceUseCase -> IUseCase
FindOneDeviceUseCase -> IDeviceRepository

FindManyDeviceUseCase -> IUseCase
FindManyDeviceUseCase -> IDeviceRepository

DevicesController -> businessLogic
DevicesController -> IDeviceRepository

@enduml