@startuml SensorsService_BusinessLogic_Code
title SmartHome Sensors Controller Code Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Boundary(businessLogic, "Business Logic") {
  class RegisterSensorUseCase {
  }

  class UpdateSensorUseCase {
  }

  class DeleteSensorUseCase {
  }

  class FindOneSensorUseCase {
  }

  class FindManySensorUseCase {
  }

  interface ISensorRepository {
    + update()
    + create()
    + remove()
    + findOne()
    + findMany()
  }

  interface IUseCase {
    + execute()
  }
}

class SensorsController {
  + registerSensor()
  + updateSensor()
  + deleteSensor()
  + findOneSensor()
  + findManySensor()
}

RegisterSensorUseCase -> IUseCase
RegisterSensorUseCase -> ISensorRepository

UpdateSensorUseCase -> IUseCase
UpdateSensorUseCase -> ISensorRepository

DeleteSensorUseCase -> IUseCase
DeleteSensorUseCase -> ISensorRepository

FindOneSensorUseCase -> IUseCase
FindOneSensorUseCase -> ISensorRepository

FindManySensorUseCase -> IUseCase
FindManySensorUseCase -> ISensorRepository

SensorsController -> businessLogic
SensorsController -> ISensorRepository

@enduml