@startuml
title SmartHome Context Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Context.puml

Person(user, "User", "A user of the system")
Person(sensor, "Sensor", "")

System(SmartHomeSystem, "SmartHome System", "System managing home and sensors")
System_Ext(api, "Notification API", "External API for notifications")

Rel(user, SmartHomeSystem, "")
Rel(SmartHomeSystem, sensor, "")
Rel(sensor, SmartHomeSystem, "")
Rel(SmartHomeSystem, api, "Uses external API to notify users about changes")

@enduml