@startuml C4_Context
title SmartHome Context Diagram

top to bottom direction

!include https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Context.puml

Person(user, "User", "A user of the system")
Person(sensor, "Sensor", "A sensors in the house")

System(SmartHomeSystem, "SmartHome System", "System managing home and sensors")
System_Ext(api, "Notification API", "External API for notifications")

Rel(user, SmartHomeSystem, "Uses the system")
Rel(SmartHomeSystem, sensor, "Sends commands to the sensor")
Rel(SmartHomeSystem, api, "Uses external API to notify users about changes")

@enduml